In [4]:
import numpy as np

x = np.array([1,2,3,4])
print(x)
print(x.ndim) #To check the dimension of the array 

[1 2 3 4]
1


In [4]:
%timeit [j**4 for j in range(0, 9)]

1.2 µs ± 27.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [2]:
import numpy as np
l = []
for i in range(1,5) :
    x = int(input("Enter - "))
    l.append(x)
    
print(np.array(l))

Enter -  1
Enter -  2
Enter -  3
Enter -  4


[1 2 3 4]


In [6]:
l = np.array([[1,2,3,4],[1,2,3,4]]) #The number of elements in each sub array should be same otherwise error 
print(l)
print(l.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [10]:
arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


In [5]:
import numpy as np
ar_zero = np.zeros(4)
ar_zeroo = np.zeros((3,4))
print(ar_zero)
print()
print(ar_zeroo)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
ar_one = np.ones(4)
ar_ones = np.ones((3,4))
print(ar_one)
print()
print(ar_ones)

[1. 1. 1. 1.]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
ar_em = np.empty(4)
print(ar_em) # creates empty array with values saved in previous code

[1. 1. 1. 1.]


In [14]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [16]:
ar_dia = np.eye(4)
print(ar_dia)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
